# Generated by Django 3.0.4 on 2020-05-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50, verbose_name='')),
                ('your_email', models.EmailField(max_length=254, verbose_name='')),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='')),
                ('message', models.TextField(verbose_name='')),
            ],
        ),
    ]
